### ISSUE TITLE
Cannot read property 'INT16' of undefined

### ISSUE THREAD

**Issue by bastaware** [lance-gg/asteroids#1]
After cloning and npm install + npm run build I get:

Spaaace + Lancegame is working fine

npm start

> lance-asteroids@2.0.0 start /Users/christian/temp/asteroids
> babel-node main.js --presets es2015

Listening on 3000
/Users/christian/temp/asteroids/node_modules/lance-gg/es5/serialize/Serializable.js:165
                            throw _iteratorError;
                            ^

TypeError: Cannot read property 'INT16' of undefined
    at Function.get (/Users/christian/temp/asteroids/src/common/Asteroid.js:11:45)
    at Asteroid.serialize (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/serialize/Serializable.js:64:41)
    at Serializable.serialize (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/serialize/Serializable.js:113:77)
    at NetworkedEventCollection.serialize (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/serialize/Serializable.js:130:69)
    at NetworkedEventCollection.serialize (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/serialize/Serializable.js:77:39)
    at NetworkTransmitter.serializePayload (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/network/NetworkTransmitter.js:104:60)
    at AsteroidsServerEngine.serializeUpdate (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/ServerEngine.js:366:44)
    at AsteroidsServerEngine.step (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/ServerEngine.js:229:36)
    at Scheduler.callTick (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/lib/Scheduler.js:94:26)
    at Scheduler.nextTick (/Users/christian/temp/asteroids/node_modules/lance-gg/es5/lib/Scheduler.js:82:18)

**Comment by namel** [comment]
Asteroids is now fixed (and pointing to Lance v3 official)
Please pull the latest code, re-run npm install and run again.
